image: "python:3.9"

before_script:
  - python --version
  - pip install -r requirements.txt

stages:
  - check
#  - build
  - test
#  - deploy

flake8:
  stage: check
  script:
  - flake8 --max-line-length=120 hokonui/exchanges/*.py

unit-test-job:   # This job runs in the test stage.
  stage: test    # It only starts when the job in the build stage completes successfully.
  script:
    - echo "Running unit tests... This will take about 60 seconds."
    - pytest tests/test_liquid.py --cov && pytest tests/test_bittrex.py --cov && pytest tests/test_hitbtc.py --cov
    - echo "Code coverage is NOT CALCULATED YET"
