name: Lint Code Base

on: [push, pull_request]

jobs:
  pylint:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'  # Specify the Python version you need

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint

    - name: Run pylint
      id: pylint
      run: |
        pylint_output=$(pylint **/*.py)
        echo "$pylint_output"
        pylint_score=$(echo "$pylint_output" | grep "Your code has been rated at" | grep -oP '\d+\.\d+')
        echo "Pylint score: $pylint_score"
        if (( $(echo "$pylint_score < 8" | bc -l) )); then
          echo "Pylint score is less than 8, failing the build."
          exit 1
        fi

    - name: Upload pylint results
      if: failure()
      with:
        name: pylint-output
        path: pylint-output.txt
      run: echo "$pylint_output" > pylint-output.txt
